import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Job Case</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi amet architecto iusto nemo ullam. Rem necessitatibus laudantium rerum nemo, vel nihil dolorem aperiam? Quia, ipsa! Praesentium sit, nemo provident repellat, sequi, quis laboriosam dolorum suscipit consequatur sed soluta iste reprehenderit.</h1>

    </div>
  )
}
